function remote_init()
	local items={
		{name="Keyboard", input="keyboard"},
		{name="Keyboard1", input="keyboard"},
		{name="Fader 1", input="value", min=0, max=127},
		{name="Fader 2", input="value", min=0, max=127},
		{name="Fader 3", input="value", min=0, max=127},
		{name="Fader 4", input="value", min=0, max=127},
		{name="Fader 5", input="value", min=0, max=127},
		{name="Fader 6", input="value", min=0, max=127},
		{name="Fader 7", input="value", min=0, max=127},
		{name="Fader 8", input="value", min=0, max=127},
		{name="Fader 9", input="value", min=0, max=127},
		{name="Fader 10", input="value", min=0, max=127},
		{name="Fader 11", input="value", min=0, max=127},
		{name="Fader 12", input="value", min=0, max=127},
		{name="Fader 13", input="value", min=0, max=127},
		{name="Fader 14", input="value", min=0, max=127},
		{name="Fader 15", input="value", min=0, max=127},
		{name="Fader 16", input="value", min=0, max=127},
		{name="Fader 17", input="value", min=0, max=127},
		{name="Fader 18", input="value", min=0, max=127},
		{name="Fader 19", input="value", min=0, max=127},
		{name="Fader 20", input="value", min=0, max=127},
		{name="Fader 21", input="value", min=0, max=127},
		{name="Fader 22", input="value", min=0, max=127},
		{name="Fader 23", input="value", min=0, max=127},
		{name="Fader 24", input="value", min=0, max=127},
		{name="Fader 25", input="value", min=0, max=127},
		{name="Fader 26", input="value", min=0, max=127},
		{name="Fader 27", input="value", min=0, max=127},
		{name="Fader 28", input="value", min=0, max=127},
		{name="Fader 29", input="value", min=0, max=127},
		{name="Fader 30", input="value", min=0, max=127},
		{name="Fader 31", input="value", min=0, max=127},
		{name="Fader 32", input="value", min=0, max=127},
		{name="Fader 33", input="value", min=0, max=127},
		{name="Fader 34", input="value", min=0, max=127},
		{name="Fader 35", input="value", min=0, max=127},
		{name="Fader 36", input="value", min=0, max=127},
		{name="Fader 37", input="value", min=0, max=127},
		{name="Fader 38", input="value", min=0, max=127},
		{name="Fader 39", input="value", min=0, max=127},
		{name="Fader 40", input="value", min=0, max=127},
		{name="Fader 41", input="value", min=0, max=127},
		{name="Fader 42", input="value", min=0, max=127},
		{name="Fader 43", input="value", min=0, max=127},
		{name="Fader 44", input="value", min=0, max=127},
		{name="Fader 45", input="value", min=0, max=127},
		{name="Fader 46", input="value", min=0, max=127},
		{name="Fader 47", input="value", min=0, max=127},
		{name="Fader 48", input="value", min=0, max=127},
		{name="Fader 49", input="value", min=0, max=127},
		{name="Encoder 1", input="value", min=0, max=127},
		{name="Encoder 2", input="value", min=0, max=127},
		{name="Encoder 3", input="value", min=0, max=127},
		{name="Encoder 4", input="value", min=0, max=127},
		{name="Encoder 5", input="value", min=0, max=127},
		{name="Encoder 6", input="value", min=0, max=127},
		{name="Encoder 7", input="value", min=0, max=127},
		{name="Encoder 8", input="value", min=0, max=127},
		{name="Fader 50", input="value", min=0, max=127},
		{name="Fader 51", input="value", min=0, max=127},
		{name="Fader 52", input="value", min=0, max=127},
		{name="Fader 53", input="value", min=0, max=127},
		{name="Fader 54", input="value", min=0, max=127},
		{name="Fader 55", input="value", min=0, max=127},
		{name="Fader 56", input="value", min=0, max=127},
		{name="Fader 57", input="value", min=0, max=127},
		{name="Fader 58", input="value", min=0, max=127},
		{name="Fader 59", input="value", min=0, max=127},
		{name="Fader 60", input="value", min=0, max=127},
		{name="Fader 61", input="value", min=0, max=127},
		{name="Fader 62", input="value", min=0, max=127},
		{name="Fader 63", input="value", min=0, max=127},
		{name="Fader 64", input="value", min=0, max=127},
		{name="Fader 65", input="value", min=0, max=127},
		{name="Fader 66", input="value", min=0, max=127},
		{name="Fader 67", input="value", min=0, max=127},
		{name="Fader 68", input="value", min=0, max=127},
		{name="Fader 69", input="value", min=0, max=127},
		{name="Fader 70", input="value", min=0, max=127},
		{name="Fader 71", input="value", min=0, max=127},
		{name="Fader 72", input="value", min=0, max=127},
		{name="Fader 73", input="value", min=0, max=127},
		{name="Fader 74", input="value", min=0, max=127},
		{name="Fader 75", input="value", min=0, max=127},
		{name="Fader 76", input="value", min=0, max=127},
		{name="Fader 77", input="value", min=0, max=127},
		{name="Fader 78", input="value", min=0, max=127},
		{name="Fader 79", input="value", min=0, max=127},
		{name="Fader 80", input="value", min=0, max=127},
		{name="Fader 81", input="value", min=0, max=127},
		{name="Fader 82", input="value", min=0, max=127},
		{name="Fader 83", input="value", min=0, max=127},
		{name="Fader 84", input="value", min=0, max=127},
		{name="Fader 85", input="value", min=0, max=127},
		{name="Fader 86", input="value", min=0, max=127},
		{name="Fader 87", input="value", min=0, max=127},
		{name="Fader 88", input="value", min=0, max=127},
		{name="Fader 89", input="value", min=0, max=127},
		{name="Fader 90", input="value", min=0, max=127},
		{name="Fader 91", input="value", min=0, max=127},
		{name="Fader 92", input="value", min=0, max=127},
		{name="Fader 93", input="value", min=0, max=127},
		{name="Fader 94", input="value", min=0, max=127},
		{name="Fader 95", input="value", min=0, max=127},
		{name="Fader 96", input="value", min=0, max=127},
		{name="Fader 97", input="value", min=0, max=127},
		
	}
	remote.define_items(items)

	local inputs={
		{pattern="b? 01 xx", name="Fader 1"},
		{pattern="b? 02 xx", name="Fader 2"},
		{pattern="b? 03 xx", name="Fader 3"},
		{pattern="b? 04 xx", name="Fader 4"},
		{pattern="b? 05 xx", name="Fader 5"},
		{pattern="b? 06 xx", name="Fader 6"},
		{pattern="b? 07 xx", name="Fader 7"},
		{pattern="b? 08 xx", name="Fader 8"},
		{pattern="b? 09 xx", name="Fader 9"},
		{pattern="b? 0a xx", name="Fader 10"},
		
		{pattern="b? 0b xx", name="Fader 11"},
		{pattern="b? 0c xx", name="Fader 12"},
		{pattern="b? 0d xx", name="Fader 13"},
		{pattern="b? 0e xx", name="Fader 14"},
		{pattern="b? 0f xx", name="Fader 15"},
		{pattern="b? 10 xx", name="Fader 16"},
		{pattern="b? 11 xx", name="Fader 17"},
		{pattern="b? 12 xx", name="Fader 18"},
		{pattern="b? 13 xx", name="Fader 19"},
		{pattern="b? 14 xx", name="Fader 20"},
		
		{pattern="b? 15 xx", name="Fader 21"},
		{pattern="b? 16 xx", name="Fader 22"},
		{pattern="b? 17 xx", name="Fader 23"},
		{pattern="b? 18 xx", name="Fader 24"},
		{pattern="b? 19 xx", name="Fader 25"},
		{pattern="b? 1a xx", name="Fader 26"},
		{pattern="b? 1b xx", name="Fader 27"},
		{pattern="b? 1c xx", name="Fader 28"},
		{pattern="b? 1d xx", name="Fader 29"},
		{pattern="b? 1e xx", name="Fader 30"},

		{pattern="b? 1f xx", name="Fader 31"},
		{pattern="b? 20 xx", name="Fader 32"},
		{pattern="b? 21 xx", name="Fader 33"},
		{pattern="b? 22 xx", name="Fader 34"},
		{pattern="b? 23 xx", name="Fader 35"},
		{pattern="b? 24 xx", name="Fader 36"},
		{pattern="b? 25 xx", name="Fader 37"},
		{pattern="b? 26 xx", name="Fader 38"},
		{pattern="b? 27 xx", name="Fader 39"},
		{pattern="b? 28 xx", name="Fader 40"},
		{pattern="b? 29 xx", name="Fader 41"},
		{pattern="b? 2a xx", name="Fader 42"},
		{pattern="b? 2b xx", name="Fader 43"},
		{pattern="b? 2c xx", name="Fader 44"},
		{pattern="b? 2d xx", name="Fader 45"},
		{pattern="b? 2e xx", name="Fader 46"},
		{pattern="b? 2f xx", name="Fader 47"},
		{pattern="b? 30 xx", name="Fader 48"},
		{pattern="b? 31 xx", name="Fader 49"},

		{pattern="9? xx 00", name="Keyboard", value="0", note="x", velocity="64"},
		{pattern="9? xx 00", name="Keyboard1", value="0", note="20", velocity="64"},
		{pattern="<100x>? yy zz", name="Keyboard"},
		
		{pattern="b? 32 xx", name="Encoder 1"},
		{pattern="b? 33 xx", name="Encoder 2"},
		{pattern="b? 34 xx", name="Encoder 3"},
		{pattern="b? 35 xx", name="Encoder 4"},
		{pattern="b? 36 xx", name="Encoder 5"},
		{pattern="b? 37 xx", name="Encoder 6"},
		{pattern="b? 38 xx", name="Encoder 7"},
		{pattern="b? 39 xx", name="Encoder 8"},
		
		{pattern="b? 3a xx", name="Fader 50"},
		{pattern="b? 3b xx", name="Fader 51"},
		{pattern="b? 3c xx", name="Fader 52"},
		{pattern="b? 3d xx", name="Fader 53"},
		{pattern="b? 3e xx", name="Fader 54"},
		{pattern="b? 3f xx", name="Fader 55"},
		{pattern="b? 40 xx", name="Fader 56"},
		{pattern="b? 41 xx", name="Fader 57"},
		{pattern="b? 42 xx", name="Fader 58"},
		{pattern="b? 43 xx", name="Fader 59"},
		{pattern="b? 44 xx", name="Fader 60"},
		{pattern="b? 45 xx", name="Fader 61"},
		{pattern="b? 46 xx", name="Fader 62"},
		{pattern="b? 47 xx", name="Fader 63"},
		{pattern="b? 48 xx", name="Fader 64"},
		{pattern="b? 49 xx", name="Fader 65"},
		{pattern="b? 4a xx", name="Fader 66"},
		{pattern="b? 4b xx", name="Fader 67"},
		{pattern="b? 4c xx", name="Fader 68"},
		{pattern="b? 4d xx", name="Fader 69"},
		{pattern="b? 4e xx", name="Fader 70"},
		{pattern="b? 4f xx", name="Fader 71"},
		{pattern="b? 50 xx", name="Fader 72"},
		{pattern="b? 51 xx", name="Fader 73"},
		{pattern="b? 52 xx", name="Fader 74"},
		{pattern="b? 53 xx", name="Fader 75"},
		{pattern="b? 54 xx", name="Fader 76"},
		{pattern="b? 55 xx", name="Fader 77"},
		{pattern="b? 56 xx", name="Fader 78"},
		{pattern="b? 57 xx", name="Fader 79"},
		{pattern="b? 58 xx", name="Fader 80"},
		{pattern="b? 59 xx", name="Fader 81"},
		{pattern="b? 5a xx", name="Fader 82"},
		{pattern="b? 5b xx", name="Fader 83"},
		{pattern="b? 5c xx", name="Fader 84"},
		{pattern="b? 5d xx", name="Fader 85"},
		{pattern="b? 5e xx", name="Fader 86"},
		{pattern="b? 5f xx", name="Fader 87"},
		{pattern="b? 60 xx", name="Fader 88"},
		{pattern="b? 61 xx", name="Fader 89"},
		{pattern="b? 62 xx", name="Fader 90"},
		{pattern="b? 63 xx", name="Fader 91"},
		{pattern="b? 64 xx", name="Fader 92"},
		{pattern="b? 65 xx", name="Fader 93"},
		{pattern="b? 66 xx", name="Fader 94"},
		{pattern="b? 67 xx", name="Fader 95"},
		{pattern="b? 68 xx", name="Fader 96"},
		{pattern="b? 69 xx", name="Fader 97"},
	}
	remote.define_auto_inputs(inputs)
end

function remote_probe()
	return {
		request="f0 7e 7f 06 01 f7",
		response="f0 7e 7f 06 02 56 66 66 01 01 ?? ?? ?? ?? f7"
	}
end
